apiVersion: v1
kind: Service
metadata:
  name: devops-dashboard-service
spec:
  ports:
  - nodePort: 30080
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: devops-dashboard
  type: NodePort
